recode_variables <- function(x){
  car::recode(x,
  recodes =
    "'q_111'='cutaneous symptoms';
     'q_111_angioedema'= 'angioedema';
     'q_111_erythema_flush_v5' = 'flush';
     'q_111_pruritus' = 'pruritus';
     'q_111_urticaria' = 'urticaria';
     'q_111_conjunctivitis_v5' = 'cojunctivitis';
     'q_112' = 'gastrointestinal symptoms';
     'q_114_dizziness'='dizziness';
     'q_114_loss_of_consciousness'='loss of consciousness';
     'q_112_abdominal_pain'='abdominal pain';
     'q_113_wheezing_expiratory_distress_v5'='expiratory distress';
      'q_522_volume'='volume iv.';
      'q_561_hospital_admission_v6'='hospital admission';
      'q_562_intensive_care_v6'='intensive care';
  'q_112_nausea' = 'nausea';
                                             'q_113_throat_tightness_v5' = 'throat tightness';
                                             'q_114_reductions_of_alertness' = 'reduced allertness';
                                             'q_112_incontinence' = 'incontinence';
                                             'q_112_abdominal_pain' = 'abdominal pain';
                                             'q_112_diarrhoea' = 'diarrhoea';
                                             'q_113_wheezing_expiratory_distress_v5' = 'expiratory distress';
                                             'q_113_rhinitis_v5' = 'rhinitis';
                                             'q_114_dizziness' = 'dizziness';
                                             'q_114_hypotension_collapse_v5' = 'hypotension';
  'q_112_dysphagia_v5' = 'dysphagia';
  'q_112_vomiting' = 'vomiting';
  'q_113' = 'respiratory symptoms';
  'q_113_respiratory_arrest' = 'respiratory arrest';
  'q_113_dyspnea' = 'dyspnea';
  'q_113_chest_tightness_v5' = 'chest tightness';
  'q_113_cough_v5' = 'cough';
  'q_113_change_in_voice_v5' = 'change in voice';
  'q_113_stridor_inspiratory' = 'inspiratory stridor';
  'q_114' = 'cardiologic symptoms';
  'q_114_chest_pain_angina_v5' = 'chest pain';
  'q_114_palpitations_cardiac_arrythmia_v5' = 'cardiac arrythmia';
  'q_114_cardiac_arrest' = 'cardiac arrest';
  'q_114_tachycardia' = 'tachycardia';
  'q_115_dysarthria_v6' = 'dysarthria';
  'q_115_dysphonia_v6' = 'dysphonia';
  'q_115_hot_sweat_tremble_v6' = 'hot sweat';
  'q_115_tingle_hands_feet_paresthesia_v6' = 'paresthesia';
  'q_115_sight_disorder_v6' = 'sight diorder';
  'q_115_agony_v6' = 'agonizing pain';
  'q_115_cyanosis_pallor_v6' = 'cyanosis';
      'q_521_autoinj_v5' = 'adrenaline autoinjector';
  'q_522_adren_iv'   = 'adrenaline i.v. 1st';
  'q_552_adren_iv_v5'   = 'adrenaline i.v. 2nd';
  'q_521_other_v5'   = 'other drugs 1st';
  'q_521_antih_v5'   = 'antihistmines 1st';
  'q_522_adren_im'   = 'adrenaline i.m. 1st';
  'q_522_antih_oral'   = 'antihistamines p.o. 1st';
  'q_552_adren_im_v5'   = 'adrenaline i.m. 2nd';
  'q_552_beta2_inhal_v5'   = 'β-blockers inh. 2nd';
  'q_521_cortic_v5'   = 'corticosteroids 1st';
  'q_552_antih_oral_v5'   = 'antihistamines p.o. 2nd';
  'q_552_cortico_oral_v5'   = 'corticosteroids p.o. 2nd';
  'q_552_volume_v5'   = 'volume i.v. 2nd';
  'q_552_adren_inhal_v5'   = 'adrenaline inh. 2nd';
  'q_552_beta2_iv_v5'   = 'β-blockers i.v. 2nd';
  'q_552_o2_v5'   = '100% oxygen 2nd';
  'q_522_o2'   = '100% oxygen 1st';
  'q_522_beta2_inhal'   = 'β-blockers inh. 1st';
  'q_521_beta2_v5'   = 'β-blockers 1st';
  'q_552_cortico_iv_v5'   = 'corticosteroids i.v. 2nd';
  'q_552_antih_iv_v5'   = 'antihistamines i.v. 2nd'
  "
  )
}
